In [1]:
#METHODES DE NDARRAY
import numpy as np

In [32]:
np.random.seed(0)
A = np.random.randint(0, 10, [2, 3])
A

array([[5, 0, 3],
       [3, 7, 9]])

In [33]:
#faire la somme de tout les éléments
A.sum()

27

In [34]:
#puis l'utiliser sur un des axes de notre tableau, ici sur l'axe 0 donc (5+3; 0+7; 3+9) de notre trableau précédent

A.sum(axis=0)

array([ 8,  7, 12])

In [35]:
#axis1 ==(5+0+3; 3+7+9)
A.sum(axis=1)

array([ 8, 19])

In [36]:
# la somme cumulé
A.cumsum()

array([ 5,  5,  8, 11, 18, 27])

In [37]:
#le produit de A
A.prod()

0

In [38]:
#produit cumulé
A.cumprod()

array([5, 0, 0, 0, 0, 0])

In [39]:
#le minimum
A.min()

0

In [40]:
#minimum d'un axe(ici on compare toujours nos nombre à la verticale)
A.min(axis=0)

array([3, 0, 3])

In [41]:
#trouver la position du min
A.argmin(axis=0)


array([1, 0, 0], dtype=int64)

In [42]:
#argsort() = va nous retourner la façon placer nos différents index afin de trier nos tableaux soit de plus petit au plus grand ou de plus grand au plus petits
#il retourne les index dans l'ordre de tri du Tableau A  sans modifier le tableau A(il n'est pas trier)

In [43]:
A.argsort()


array([[1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [44]:
A.argsort(axis=0)

array([[1, 0, 0],
       [0, 1, 1]], dtype=int64)

In [45]:
A.argmin(axis=0)

array([1, 0, 0], dtype=int64)

In [46]:
#pour accéder aux autres fonction en dehors de ndarray
#np.exponentielle à l'int. du quel on fait passer notre tableau(on va donc avoir le nombre exp pour chaque nombre à l'int. de notre tableau A)
np.exp(A)

array([[1.48413159e+02, 1.00000000e+00, 2.00855369e+01],
       [2.00855369e+01, 1.09663316e+03, 8.10308393e+03]])

In [47]:
#erreur parceque l'algorythme de 0 n'existe pas
np.log(A)

C:\Users\JoJo_\AppData\Local\Temp\ipykernel_24540\1028426564.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(A)


array([[1.60943791,       -inf, 1.09861229],
       [1.09861229, 1.94591015, 2.19722458]])

In [48]:
#cosinus
np.cos(A)

array([[ 0.28366219,  1.        , -0.9899925 ],
       [-0.9899925 ,  0.75390225, -0.91113026]])

In [49]:
#sinus
np.sin(A)

array([[-0.95892427,  0.        ,  0.14112001],
       [ 0.14112001,  0.6569866 ,  0.41211849]])

In [50]:
#sinus hyperbolique
np.sinh(A)

array([[  74.20321058,    0.        ,   10.01787493],
       [  10.01787493,  548.31612327, 4051.54190208]])

In [51]:
#Statistiques avec Numpy


In [52]:
A

array([[5, 0, 3],
       [3, 7, 9]])

In [53]:
#la moyenne(méthodes de numpy)
A.mean()

4.5

In [54]:
#l'écart type  de notre tableau ; fait partie des méthodes qu'ona sur l'objet NUMPY
A.std()

2.9297326385411577

In [55]:
#LA VARIANCE(méthodes de numpy)
A.var()

8.583333333333334

In [56]:
#Corrélation coefficient = une fonction numpy qui permet de tracer une matrice de corrélation pour notre tableau A
#on va comprendre les corrélations qu'il ya entre les différents lignes/colonnes (en fonction de l'axe choisi dans notre tableau A)
#ou mêmes entre les différents lignes / colonnes de n'importe quel tableau différents dans numpy

In [57]:
#indique la corrélation qui existent entre les différents lignes de A
np.corrcoef(A)

array([[ 1.        , -0.56362148],
       [-0.56362148,  1.        ]])

In [58]:
#accéder au nombre d'en haut à droite, donc a la premiière ligne 0 et deuxième colonne 1
np.corrcoef(A) [0, 1]

-0.5636214801906779

In [59]:
#on va maintenant trouver  le nombre de fois qu'un élément de notre tableau numpy se répète 
#np.unique nous retourne les différents entités dans notre tableau et à la fois les répétitions pour chacune de ces entités 


np.unique(A, return_counts=True)
#on aurait donc 2 tableaux numpy. le 1er: les différents entités qu'on a dans notre tableau puis le deuxième le nombre de répétition de chacune de ces entités

(array([0, 3, 5, 7, 9]), array([1, 2, 1, 1, 1], dtype=int64))

In [60]:
np.random.seed(0)
B = np.random.randint(0, 10, [5, 5])
B

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

In [61]:
np.unique(B, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 2, 1, 3, 2, 3, 2, 4, 4, 3], dtype=int64))

In [62]:
#maintenant on va arrnger ces tableaux dans une variable
#'values' égale au 1er tableau et 'counts' au 2eme

values, counts = np.unique(B, return_counts=True)

In [63]:
counts

array([1, 2, 1, 3, 2, 3, 2, 4, 4, 3], dtype=int64)

In [64]:
#le but serait de classer nos variables pour savoir quel sont les éléments qui apparaissent le +/- souvent dans notre dataset  
#ici argsort nous donne un tableau des différents index qui permet de trier 'counts'.
#ici on a les index trier du plus petit au plus gros
counts.argsort()

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8], dtype=int64)

In [65]:
#on va injecter tout ces index dans un tableau values, et ca va donc retrier values

values[counts.argsort()]
#ici le nombre qui apparait le plus souvent c'est le nombre 8

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8])

In [72]:
#counts[counts.argsort()] = permet d'indirectement trier counts

for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'valeur {i} apparait {j}')

valeur 0 apparait 1
valeur 2 apparait 1
valeur 1 apparait 2
valeur 4 apparait 2
valeur 6 apparait 2
valeur 3 apparait 3
valeur 5 apparait 3
valeur 9 apparait 3
valeur 7 apparait 4
valeur 8 apparait 4


In [73]:
#NAN CORRECTIONS = ("not a number" correction)

A = np.random.randn(5, 5)
A[0, 2] = np.nan
A[4, 3] = np.nan
A

array([[ 0.44386323,  0.33367433,         nan, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,         nan, -0.38732682]])

In [74]:
A.mean()

nan

In [75]:
#il existe des fonctions qui permettent d'ignororer des entités NAN lors son exécution
np.nanmean(A)

0.010707879575141632

In [76]:
np.nanvar(A)

1.213857100788078

In [77]:
np.nanstd(A)

1.1017518326683546

In [78]:
#ici on va compter le nombre de fois qu'apparraise l'entité NAN dans notre tableau

np.isnan(A)
#True dans notre masque Boolean signifie la présence de NAN

array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [79]:
np.isnan(A).sum()
#dans  tout le tableau numpy y'a 2 fois NAN

2

In [80]:
#pour conaître le rapport de NAN que l'on a et toute la taille de notre tableau
#on va diviser par la taille de notre tableau en utilisant l'attribu 'size'
np.isnan(A).sum()/A.size

#on a 8% de tout le tableau qui est un NAN

0.08

In [83]:
#on va débarrasser de NAN dans un tableau numpy en utilisant "BOOLEAN INDEXING" de numpy


A[np.isnan(A)] = 0

#on va injecter le masque dans notre tableau A puis est égale à une valeur par défaut par exemple 0
#dans le résultat le 0 va donc remplacer le NAN

A

array([[ 0.44386323,  0.33367433,  0.        , -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  0.        , -0.38732682]])

In [85]:
#Algèbre LINEAIRESPARTIE DU COURS OPTIONNEL ET PAS LE PLUS IMPORTANT EN DATA SCIENCE

A = np.ones((2, 3))
B = np.ones((3, 2))

A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [86]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [87]:
#Ici on cherche l'attribut T de transposer une autre matrice(ici de A à B)

A.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [88]:
A.T.shape


(3, 2)

In [89]:
#Maintenant on va faire un produit matricielle entre A et B ave la méthode ".dot"
A.dot(B)

array([[3., 3.],
       [3., 3.]])

In [90]:
B.dot(A)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [231]:
A = np.random.randint(0, 10, [3, 3])

A


array([[3, 1, 0],
       [1, 0, 8],
       [8, 5, 3]])

In [232]:
np.linalg.det(A)

-58.999999999999964

In [233]:
#retourne l'inverse de notre matrice
np.linalg.inv(A)


array([[ 0.6779661 ,  0.05084746, -0.13559322],
       [-1.03389831, -0.15254237,  0.40677966],
       [-0.08474576,  0.11864407,  0.01694915]])

In [235]:
#souvent en data science, les combinaisons linéaires peut empecher l'inversion donc on peut utiliser la fonction pseudo inverse "pinv()"
#avec quleque différences qu'il va falloir connaitre
np.linalg.pinv(A)

array([[ 0.6779661 ,  0.05084746, -0.13559322],
       [-1.03389831, -0.15254237,  0.40677966],
       [-0.08474576,  0.11864407,  0.01694915]])

In [236]:
#Prinicipal Component Analysis = utilise les valeurs/vecteurs propres(réduction de dimension)
np.linalg.eig(A)
#1ere tableau = les 3 valeurs propres
#2eme tableau = nos 3 vecteurs propres 

(array([ 8.86011467,  1.52021723, -4.3803319 ]),
 array([[-0.11481653, -0.54597106,  0.11884177],
        [-0.67283801,  0.80791857, -0.87709169],
        [-0.73082568,  0.22177285,  0.46538887]]))