In [1]:
#Built-in functions
#eg print()
#abs() qui retourne la valeur absolue de la valuer qu'on indique en argument


In [2]:
x = -3
abs(x)

3

In [3]:
x= 3.14
round(x)

3

In [1]:
liste_1 = [0, 3, 34, -20]

In [2]:
max(liste_1)

34

In [3]:
min(liste_1)

-20

In [5]:
#the key parameter is used to specify a function (in this case, len) to extract a comparison key for each element. 
#The min() function then finds the element with the smallest key value.

fruits = ["apples", "cherries", "kiwi",  "banana"]
min (fruits, key=len)

'kiwi'

In [6]:
len(liste_1)

4

In [7]:
sum(liste_1) #sum de tout les éléments

17

In [8]:
liste_2 = [True, True, False]

In [9]:
all(liste_2)#retourne la function TRUE quand tout les éléments sont TRUE

False

In [10]:
any(liste_2) #retorune la function TRUe quand au moins un des éléments est lui même égale à TRUE 

True

In [11]:
#0 = FALSE
#toute autre valeur est égale à TRUE

In [12]:
any(liste_1)

True

In [13]:
x = 10 #type int
type(x) #'type' retourne le type de la variable

int

In [14]:
x = str(x) #de transformer 'int' en 'str' par exemple

In [15]:
x #le int est dont transformé en str avec ses ''

'10'

In [16]:
type(x) #et maintenant en vérifiant il est bien un str 

str

In [17]:
y = '20'
y = int(y)

In [18]:
y

20

In [19]:
type(y)

int

In [20]:
#on peut pas convertir tout en nombre entier eg
x = 'bonjour'
x = int('bonjour')

ValueError: invalid literal for int() with base 10: 'bonjour'

In [14]:
x = 10 #on convertit un nombre entier en nombre décimal  avec 'float'
float(x)
x

10

In [15]:
type(x)

int

In [13]:
x = 10 #on convertit un nombre entier en nombre décimal  avec 'float'
float(x)
print(float(x))

10.0


In [17]:
type(float(x))

float

In [22]:
#quand on écrit "liste/tuple_1,2,3 etc" c'est parceque "list/tuple" sont des fonctions déjà protégés en python

In [23]:
liste_1 = [0, 61, 63, 243]

In [24]:
tuple(liste_1)#on convertit la liste en tuple

(0, 61, 63, 243)

In [19]:
tuple_1 = tuple(liste_1)
tuple_1

(0, 3, 34, -20)

In [26]:
list(tuple_1)

[0, 61, 63, 243]

In [27]:
inventaire = {
    "bananes" : 5000,
    "pommes" : 2094,
    "poires" : 412809
}

In [28]:
list(inventaire.keys())

['bananes', 'pommes', 'poires']

In [29]:
bin(15)# convert un int en nombre binaire

'0b1111'

In [30]:
oct(15)

'0o17'

In [31]:
hex(15)#convert en hexadecimal

'0xf'

In [20]:
x = input('entrez un nombre')#permet à utilisatuer du programme de mettre du texte et la fonction nous retourne un str

entrez un nombreDjovan


In [33]:
type(x)

str

In [21]:
#donc pour convertit le format pour que utilisateur puisse utiliser un int

x = int(input('entrez un nombre'))
x + 10

entrez un nombre10


20

In [35]:
type(x)

int

In [36]:
#' f"{variable visée}" / "{variable visée}".format()' permet de personnaliser des chaînes de caractères (le f au début est optionnel)

x = 25
ville = 'Paris'
message =  "La température est de x degC à Ville"
print(message)

La température est de x degC à Ville


In [37]:

x = 25
ville = 'Paris'
message =  "La température est de {} degC à {}".format(x,ville)
print(message)

La température est de 25 degC à Paris


In [38]:
#ou
x = 25
ville = 'Paris'
message = f"La température est de {x} degC à {ville}"
print(message)

La température est de 25 degC à Paris


In [39]:
import numpy as np #dictionnaire paramètres avec un réseaux de neurones très petit

parametres = {
    "W1" : np.random.randn(2, 4),
    "b1" : np.zeros((2, 1)),
    "W2" : np.random.randn(2, 2),
    "b2" : np.zeros((2, 1))
}

In [40]:
for i in range(1,3):
    print("couche", i)
    print(parametres["W{}".format(i)])

couche 1
[[-0.50616575  0.58524718 -1.61083997  0.90891314]
 [ 0.52951275  0.92816062 -1.04220023  0.37168724]]
couche 2
[[-0.8086964   0.92820671]
 [-0.84640433  0.13281662]]


In [41]:
#OU

for i in range(1,3):
    print("couche", i)
    print(parametres["W"+str(i)])#w + str de ce que contient i

couche 1
[[-0.50616575  0.58524718 -1.61083997  0.90891314]
 [ 0.52951275  0.92816062 -1.04220023  0.37168724]]
couche 2
[[-0.8086964   0.92820671]
 [-0.84640433  0.13281662]]


In [42]:
#"open()"fonction qui permet de créer/enregistrer  des fichiers sur un certains noms et ouvrir certrains fichiers
#different mode qui existe : 'r' ouvrir pour lire(default)
#'w' ouvrir pour écrire dans un fichier
#'x' ouvrir pour création , erreur si le fichier existe déjà
#'a' ouvrir pour écrire , en partant de la fin du fichier, sans supprimant (overwrite)ce qu'il y avait avant
#et d'autre mode


In [43]:
f = open('fichier.txt', 'w')
#on va créer une variable F qui est égale au résultat de la fonction open dans laquelle on va mettre 'fichier.txt' puis définir le mode ici 'w'

In [44]:
f.write('Bonjour')
#pour avoir accès aux differents méthodse pour write(w) on va écrire '.' puis cliquer sur TAB
f.close()

In [45]:
#le fichier qui va ouvrir se trouve dans mes repères de fichiers pour les cours sous "fichier.txt" avec "Bonjour" affiché dedans

In [46]:
f = open('fichier.txt', 'r')#ici le programme va lire ce qu'il y a dans le fichier auparavant
f.read()

'Bonjour'

In [47]:
with open('fichier.txt', 'r') as f:
    print(f.read())#pas besoin de mettre f.close parceque Python va le fermer automatiquement
    

Bonjour


In [48]:
with open('fichier.txt', 'w') as f:
    for i in range(10):
        f.write(i, i**2)
    

TypeError: TextIOWrapper.write() takes exactly one argument (2 given)

In [ ]:
with open('fichier.txt', 'w') as f:
    for i in range(10):
        f.write(i)
    

In [ ]:
with open('fichier.txt', 'w') as f:
    for i in range(10):
        f.write("{}^2 = {}".format(i, i**2))
        
#dans le "fichier.txt" dans mon repertoire il est complètement illisible donc avec la suite on va démontrer comment aller à la ligne
    

In [49]:
with open('fichier.txt', 'w') as f:
    for i in range(10):
        f.write("{}^2 = {} \n".format(i, i**2)) 
        


In [50]:
with open('fichier.txt', 'r') as f:
    print(f.read())

0^2 = 0 
1^2 = 1 
2^2 = 4 
3^2 = 9 
4^2 = 16 
5^2 = 25 
6^2 = 36 
7^2 = 49 
8^2 = 64 
9^2 = 81 

