In [3]:
#objet= NDARRAY en numpy le plus puissant; permet à créer des tableaux à n dimension est +

#numpy est comparable à une séquence mais inégal à une liste parceque il est bcp plus rapide, prendre moins place et donne bcp plus de méthodes pour faire des calculs

#en data science en utilise bcp les tableaux à 2 dimension. Dans nos tableaux on peut enregistrer des pixel allant de 0 à 255(0= noir à 255 = white)

#attributs leplus important en machine learning c'est l'attribut ndarray.shape(permettre à voir la forme de notre tableau(profondeurs,combien de lignes etc ) 
#ndim = 1 (dimension)
#shape = (2,)

#ndim = 2
#shape = (2,3)(2 lignes et 3 colonnes)

#ndim = 3
#shape = (2, 3, 2)(2 lignes, 3 colonnes,)

#l'attribut shape donne un tuple (une séquence avec des index). donc cc'est un attribut immutable donc en quelque sorte protégé

In [4]:
import numpy as np

In [5]:
np.array(1, 2, 3 )

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [6]:
#pour faire passer nos nombre dans notre constructeur on est obligé de utiliser '[]'

A = np.array([1, 2, 3])

A.ndim#resort sa dimesnions


1

In [7]:
A.shape#resort sa forme

(3,)

In [69]:
A.size #resort tout les éléments dans notre tableau

3

In [8]:
#initialise notre tableau avec pleins de zéros en indiquant le éléments de notre dimension de tableau en '()'

B = np.zeros((3, 2))
B 


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
B.shape

(3, 2)

In [10]:
type(B.shape)

tuple

In [74]:
C.size

12

In [75]:
#"np.full" une fonction pas super utile d'initialiser un tableau avec un certain nombre
#très rare de voir un tableau plus soit avec des 1's , des 0's ou des nombre aléatoires 
D = np.full((2, 3), 9)

D

array([[9, 9, 9],
       [9, 9, 9]])

In [76]:
#random.randn initialise nos tableaux avec des nombres issus de la distribution normale centré en 0 
#à chaque execution du code le résultat change
np.random.randn(3, 4)

array([[-0.21155631, -0.49939633, -1.07560279, -1.60669868],
       [ 1.31592995,  1.2403638 ,  2.46447632, -1.95464588],
       [ 1.27101876,  0.86343843,  0.07247885,  1.63210438]])

In [77]:
#donc la fonction seed va fixer l'aléatoire de notre code générateur

np.random.seed(0) #pour changer notre aléatoir faut juste changer le chiffre 
np.random.randn(3, 4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [78]:
#donc la fonction seed va fixer l'aléatoire de notre code constructeur

np.random.seed(3000) #pour change notre aléatoire faut juste changer le chiffre 
np.random.randn(3, 4)

array([[ 2.63020515,  0.33163518, -0.98753978,  1.19650759],
       [ 1.70517555,  0.1445731 , -0.22478908,  0.22137286],
       [ 2.0621206 ,  2.35645496,  2.34544362, -0.9736413 ]])

In [79]:
#fonction 'np.eye' =  retourne la matrice et identite (pas trop utilisé en machine learning et data)

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [80]:
#constructeur 'np.linspace()' = permet à créer une tableau à n dimension où on va préciser un point de début, un point de fin et  une quantité qu'on veut avoir dans notre tableau*

np.linspace(0, 10, 20)#20 points repartis entre 0 et 10


array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [81]:
#constructeur 'np.arange()' = permet à créer un tableau à n dimension où on va préciser un point de début, un point de fin et le pas qu'on désir sauter dans nos éléments de 0 jusqu'à 10

np.arange(0, 10, 1 )

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:

np.arange(0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [83]:
#dans numpy on peut choisir quel type de donnée on veut avoir dans notre tableau
#grace au paramètre dtype=float(datatype); on peut également choisir le nombre de bites que va occuper notre valeur
#'np.int8' on peut créer des nombres entiers qui occupent 8bites de notre mémoire ou np.int16 etc
#quelque soit le constructeur de tableau on choisit(linspace,full,arange) on peut préciser le type de donnée on veut avoir

In [84]:
np.linspace(0, 10, 20, dtype=np.float64)#on aura une grande précision dans les nombres obtenus. Le programme sera lent à l'exe


array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [85]:
np.linspace(0, 10, 20, dtype=np.float16)#on aura  moins de précision dans les nombres obtenus. Le programme sera plus rapide à l'exe


array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

In [86]:
#Différents méthodes qui nous permettent de manipuler des tableaux

In [87]:
A = np.zeros((3, 2))
B = np.ones((3, 2))

In [88]:
print(A)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [89]:
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [90]:
#assembler de façon horizontal
C = np.hstack((A, B))

In [91]:
C

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [92]:
C.shape

(3, 4)

In [93]:
#assembler le tableau de façon verticale; Affiche d'abord le tableau A puis celui du B 

D = np.vstack((A, B))

In [94]:
D

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [95]:
D.shape

(6, 2)

In [96]:
#ou concatenate qui donne le même résultat et où on va devoir désigner un axe sur lequel on veut faire sur notre assemblage
#plus facile à changer de dimension que "vstack" ou "hstack"
#et on pourra développer une meilleur compréhension sur des axes numpy
np.concatenate((A, B), axis=1)    
    

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [97]:
#".reshape" = méthode qui nous permet de remanipuler la forme d'un tableau pour lui donner un nouvel forme
#Seulement fonctionnable si le nombre d'élément qu'on a dans la forme initiale est = au nombre d'éléments qu'on a dans la forme finale

D.size

12

In [98]:
D = D.reshape((3, 4))#on écrit ces chiffres dans un tuple vu que shape doit être dans un tuple

D

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [99]:
A = np.array([1, 2, 3])
A.shape
#le 1 manquant de notre shape peut créer des problèmes dans notre algorythme donc on va reshape à la suite

(3,)

In [100]:
A = A.reshape((A.shape[0], 1))
A.shape

(3, 1)

In [101]:
#ou
A = A.reshape((3, 1))
A.shape

(3, 1)

In [102]:
#Cependant dans certains fonction comme crééer des graphiques, observer une photo à l'écran
#vaut mieux qu'il y'a le un qui est absent parcequ'il peut présenter des problèmes

In [103]:
A = A.squeeze()
#va retouner le tableau le 1 a été remplaçé par rien. Donc,il a pour fonction de disparaître toutes les dimensions finisons par 1

In [104]:
A.shape

(3,)

In [105]:
#".ravel" = méthode qui permet d'aplâtir un tableau à une seule dimension

In [106]:
#on va utiliser D de plus haut dans lequel on a 3 lignes et 4 colonnes

D.ravel()

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.])

In [107]:
#si on veut vérifier les dimensions
D.ravel().shape

(12,)