In [1]:
#Broadcastin(technique NUMPY à calculer entre Tableau A et B de façon rapide et simple. Puissant mais peut être dangereux pour le programme)
import numpy as np

In [2]:
np.random.seed(0)
A = np.random.randint(0, 10, [2,3])
B = np.ones((2,3))

In [3]:
A

array([[5, 0, 3],
       [3, 7, 9]])

In [4]:
B

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
C = A + B
C

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])

In [9]:
np.random.seed(0)
A = np.random.randint(0, 10, [2,3])
B = np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
A

array([[5, 0, 3],
       [3, 7, 9]])

In [11]:
B

array([[1., 1.],
       [1., 1.]])

In [12]:
#nos tableaux peuvent pas surposer d'où l'erreur
C = A + B
C

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [13]:
#cependant c'est possible lorsqu'on peut étendre certaine dimension de nos tableaux
#donc ici on va utiliser le broadcasting
#on ajoute A + un tableau à 2lignes et 2 colonnes(ce tableau à été étendu pour completer les dimensions de notre tableau A)
A + 2

array([[ 7,  2,  5],
       [ 5,  9, 11]])

In [14]:
#peut meme faire avec une dimension
np.random.seed(0)
A = np.random.randint(0, 10, [2,3])
B = np.ones((2,1))

In [15]:
A

array([[5, 0, 3],
       [3, 7, 9]])

In [16]:
B

array([[1.],
       [1.]])

In [18]:
A + B

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])

In [19]:

np.random.seed(0)
A = np.random.randint(0, 10, [2,3])
B = np.ones((3,1))
#meme sans mettre le 1 il est compris par le porgramme parceque le 3 serait considérer comme la dernière de notre tableau

In [20]:
A

array([[5, 0, 3],
       [3, 7, 9]])

In [21]:
B

array([[1.],
       [1.],
       [1.]])

In [22]:
A + B
#Erreur  à cause du fait que dans le Broadcasting chacune des dimension de nos tableux doit être égales de façon respectives
#A/B devraient avoir les même nombres de lignes et colonnes


ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [23]:

np.random.seed(0)
A = np.random.randint(0, 10, [4,1])
B = np.ones((1,3))

In [24]:
A

array([[5],
       [0],
       [3],
       [3]])

In [25]:
B

array([[1., 1., 1.]])

In [26]:
#ici le vecteur A et B vont mutuellement s'étendre l'un sur l'autre pour couvrir une surface de 4X3
A + B

array([[6., 6., 6.],
       [1., 1., 1.],
       [4., 4., 4.],
       [4., 4., 4.]])