In [ ]:
#CLASSIFICATION avec scatter et plt

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [82]:
iris = load_iris()

x = iris.data
y = iris.target

names = list(iris.target_names)

print(f'x contient {x.shape[0]} examples et {x.shape[1]} variables')
print(f'il y a {np.unique(y).size} classes')
x

x contient 150 examples et 4 variables
il y a 3 classes


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [83]:
iris = load_iris()

x = iris.data
y = iris.target

names = list(iris.target_names)

print(f'x contient {x.shape[0]} examples et {x.shape[1]} variables')
print(f'il y a {np.unique(y).size} classes')
y

x contient 150 examples et 4 variables
il y a 3 classes


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [84]:
#Graphique de CLASSIFICATION avec plt.scatter
#Limite: peut seulement présenter 2 des variables dans les 4 on dispose

plt.scatter(x[:, 0], x[:, 1], c=y)
plt.xlabel('longeur  sépal')
plt.ylabel('largeur sépal')

Text(0, 0.5, 'largeur sépal')

In [85]:

plt.scatter(x[:, 0], x[:, 1], c=y, alpha=0.5, s=x[:,2]*100)
#c = couleur
#alpha = controler la transparence de chacun des pts de notre graphe
#s= controler la taille de nos variables; ici on va controler la taille en fonction d'une des variables de notre problème
#plus les pts sont gros= pétals est longs; plus les pts sont petits =pétals petits
plt.xlabel('longeur  sépal')
plt.ylabel('largeur sépal')

Text(42.597222222222214, 0.5, 'largeur sépal')

In [86]:
#GRAPHIQUES 3D
from mpl_toolkits.mplot3d import Axes3D

In [87]:
#ici on doit créer un objet axe apres avoir chargé le module
ax = plt.axes(projection='3d')

In [88]:

ax = plt.axes(projection='3d')
ax.scatter(x[:,0], x[:,1], x[:, 2], c=y)
#dans spyder ou pycharmm on peut explorer la graphique(cool)

In [89]:
#mais on peut également le voir dans jupyter on commencant avec :
""""
%matplotlib
from mpl_toolkits.mplot3d import Axes3D

SyntaxError: incomplete input (1088802196.py, line 2)

In [53]:
ax = plt.axes(projection ='3d')
ax.scatter(x[:, 0], x[:, 1], x[:,2], c=y)

In [54]:
#on peut également visualiser des surfaces et des fonctions mathématiques que l'on aurait modélisé
f = lambda x, y: np.sin(x) + np.cos(x+y)

In [58]:

X = np.linspace(0, 5, 100)
Y = np.linspace(0, 5, 100)
X, Y = np.meshgrid(X, Y)

Z = f(X, Y)

In [59]:
Z.shape

(100, 100)

In [60]:
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, Z, cmap='plasma')

In [61]:
#HISTOGRAMME
#permet de voir la distribution des données avec lesquel on travail

plt.hist(x[:,0])
#bins = détermine le nombre de section qu'on souhaite avoir dans notre histogramme

(array([ 9., 23., 14., 27., 16., 26., 18.,  6.,  5.,  6.]),
 array([4.3 , 4.66, 5.02, 5.38, 5.74, 6.1 , 6.46, 6.82, 7.18, 7.54, 7.9 ]),
 <BarContainer object of 10 artists>)

In [62]:

plt.hist(x[:,0], bins=1)
#bins = détermine le nombre de section qu'on souhaite avoir dans notre histogramme

(array([150.]), array([4.3, 7.9]), <BarContainer object of 1 artists>)

In [63]:


plt.hist(x[:,0], bins=30)
#bins = détermine le nombre de section qu'on souhaite avoir dans notre histogramme

(array([ 4.,  1.,  4.,  2.,  5., 16.,  9.,  4.,  1.,  6., 13.,  8.,  7.,
         3.,  6., 10.,  9.,  7.,  5.,  2., 11.,  4.,  1.,  1.,  4.,  1.,
         0.,  1.,  4.,  1.]),
 array([4.3 , 4.42, 4.54, 4.66, 4.78, 4.9 , 5.02, 5.14, 5.26, 5.38, 5.5 ,
        5.62, 5.74, 5.86, 5.98, 6.1 , 6.22, 6.34, 6.46, 6.58, 6.7 , 6.82,
        6.94, 7.06, 7.18, 7.3 , 7.42, 7.54, 7.66, 7.78, 7.9 ]),
 <BarContainer object of 30 artists>)

In [64]:



plt.hist(x[:,0], bins=20)
plt.hist(x[:,1], bins=20)
#pour une figure on peut créer 2 histogrammes en même temps

(array([ 1.,  3.,  4.,  3.,  8., 14., 14., 10., 26., 11., 19., 12.,  6.,
         4.,  9.,  2.,  1.,  1.,  1.,  1.]),
 array([2.  , 2.12, 2.24, 2.36, 2.48, 2.6 , 2.72, 2.84, 2.96, 3.08, 3.2 ,
        3.32, 3.44, 3.56, 3.68, 3.8 , 3.92, 4.04, 4.16, 4.28, 4.4 ]),
 <BarContainer object of 20 artists>)

In [65]:
#on peut également tracer les histogrammes en 2D, pour visualiser la distribution des données lorsqu'elles suivent 2 variables
plt.hist2d(x[:,0], x[:,1])
plt.xlabel('longueur sépal')
plt.ylabel('largeur sépal')
#légende qui nous indique à quoi corréspond les différents couleurs
plt.colorbar()

In [66]:

plt.hist2d(x[:,0], x[:,1], cmap='Blues')
plt.xlabel('longueur sépal')
plt.ylabel('largeur sépal')
plt.colorbar()

In [71]:
#l'histogramme d'une analyse d'une image en noir et blanc
from scipy import misc
face = misc.face(gray=True)
#plt.imshow(face, cmap='gray')
plt.hist(face.ravel(),bins=255)#RAPPEL: 255 = valeurs de pixel dans une image 0= noir, 255 = blanc
#ravel=applatit l'image
plt.show()
#dans le résultat on voit l'analyse d'apparition des différents couleurs de pixels
#majorité entre 100  et 150, beaucoyp dans les noir et peu qui sont clairs

C:\Users\JoJo_\AppData\Local\Temp\ipykernel_9400\3000436198.py:3: DeprecationWarning: scipy.misc.face has been deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. Dataset methods have moved into the scipy.datasets module. Use scipy.datasets.face instead.
  face = misc.face(gray=True)


In [72]:
#CONTOUR PLOT
#Permet un meilleur compréhension pour l'optimisation d'une problème

plt.contour(X, Y, Z)

In [73]:
#on peut augmenter le nombre de niveau qui précisent le détails de notre graphique avec le chiffre qui suive
#et avec colors 
plt.contour(X, Y, Z, 20, colors='black')
#positif=ligne continue
#négatif=ligne petit tirait(ligne discontinue)

In [74]:
plt.contourf(X, Y, Z, 20, cmap='RdGy')
plt.colorbar()
#quels sont les valeurs de nos différents gradient sur notre contours plot 

In [75]:
#IMSHOW (Imageshow)
plt.imshow(face)#face=tableau numpy qui continent les différents px de notre image
#donc la fonction IMshow permet d'afficher n'importe quel tableau Numpy

In [76]:
#ici on va passer à la matrice pour notre dataset des fleurs iris
plt.imshow(np.corrcoef(x.T), cmap='Blues')
plt.colorbar()


In [77]:
#Exercice sur les graphiques importantes de matplotlib

classes = list(np.unique(y))
print(classes)

[0, 1, 2]


In [79]:
n = x.shape[1]#on enregistre dans le variable n le nombre de colone qu'il y a dans x(la dimension)
plt.figure(figsize=(12, 8))
for i in range (n):#boucle for qui va faire une itération sur le noimbre de variable qu'on a (n)
    plt.subplot(n//2, n//2, i+1)#(//=nombre entier) n diviser par 2 lignes; n diviser par 2 colonnes; graphique i + 1  parcequ'il n'a pas de graphique 0(n)
    plt.scatter(x[:, 0], x[:, i], c=y)#je vais plot un abscisse 0 et I pour les ordonner
    plt.xlabel('0')
    plt.ylabel(i)
    #plt.colorbar(ticks=list(np.unique(y)))

In [80]:
n = x.shape[1]#on enregistre dans le variable n le nombre de colone qu'il y a dans x(la dimension)
plt.figure(figsize=(12, 8))
for i in range (n):#boucle for qui va faire une itération sur le noimbre de variable qu'on a (n)
    plt.subplot(n//2, n//2, i+1)#//=nombre entier; ndiviser par 2 lignes; n diviser par 2 colonnes; graphique i + 1  parcequ'il n'a pas de graphique 0(n)
    plt.scatter(x[:, 0], x[:, i], c=y)#je vais plot un abscisse 0 et I pour les ordonner
    plt.xlabel('0')
    plt.ylabel(i)
    plt.colorbar(ticks=list(np.unique(y)))